### ISSUE TITLE
Show photos/assets evolution

### ISSUE THREAD

**Issue by wjdp** [newtheatre/history-project#672]
Currently we have production shots coming from a SM gallery and 'publicity materials' from the `assets` hash in the show file (containing both photographs and binary files)

This publicity materials section is really a mix of:
- Publicity materials
- Scripts
- Sound tracks
- Lighting plans
- Other associated documents

### Tasks

- [ ] Think of a new title for this section? Or perhaps just leave ambiguous.
- [ ] Design of section, perhaps work in with an evolution of the single show page.
- [ ] Deal with binary files better
  - [ ] PDF viewer for PDF files
  - [ ] Media player for music
  - [ ] Video player for video
  - [ ] All of the above require the assets are served with the correct MIME type. Something that GitHub does not do. A service – [RawGit](https://rawgit.com/) – exists for this but does not have LFS support, see https://github.com/rgrove/rawgit/issues/128. We could perhaps push assets to another repo for serving, or look at using S3/B2 ([expensive](https://www.backblaze.com/b2/cloud-storage-providers.html): $5-$20/mnth).

**Comment by samozzy** [comment]
Perhaps _Behind The Scenes_ materials - Scripts, Soundtracks, Lighting Plans, etc, as well as any 'candid' photos (not production shots). And then _Show Publicity_ which includes production shots, trailers, programmes, posters, etc.

**Comment by nhyty** [comment]
Can we not use smugmug for videos?

**Comment by wjdp** [comment]
Yes, we can and we should. Photos/Vid -> SM, everything else -> LFS

**Comment by nhyty** [comment]
Thinking about this, would calling it Show Assets or something similar be fine?

**Comment by nhyty** [comment]
https://github.com/telecomsante/pdf-viewer would this work for the pdf viewer???

**Comment by wjdp** [comment]
Could do. We are still restricted by the MIME type issue though so need to find a solution for that first.

**Comment by nhyty** [comment]
I realise that, there doesn't appear to be a free solution for this at the moment.

**Comment by wjdp** [comment]
Sadly not, though I think my cost estimate is vastly inflated. PDF viewer would be nice-to-have but as not many PDFs on site this issue isn't overly worth spending time on. (i.e. the current setup does work)
