### ISSUE TITLE
Bios todo

### ISSUE THREAD

**Issue by nhyty** [newtheatre/history-project#938]
- [x] Nick Frost - stage name Nick Farrell https://en.wikipedia.org/wiki/Nicholas_Farrell
- [x] John Turner - stage name John Benfield https://en.wikipedia.org/wiki/John_Benfield
- [x] Clive Tyldesley - https://en.wikipedia.org/wiki/Clive_Tyldesley
- [x] Hugh Simon http://spooksfans.weebly.com/hugh-simon.html

**Comment by wjdp** [comment]
_added more TODOs to issue description_

**Comment by nhyty** [comment]
Benfield and Farrell are already there, under there non stage names 😛

**Comment by wjdp** [comment]
ah I am a twit then.

We should record stage names...

**Comment by nhyty** [comment]
as you're bored ben 😃

**Comment by BenWoodford76** [comment]
Do we have/decide on a field for recording stage names?

**Comment by nhyty** [comment]
@BenWoodford76 I have put them in as comments before

**Comment by nhyty** [comment]
@nhyty See Sam hayward
